### ISSUE TITLE
Unpause script

### ISSUE THREAD

**Issue by sajanrajdev** [sajanrajdev/badger-emergency-toolkit#4]
### Description
Multisig script to call un-pause on all or specific contracts as required. The script could include a CLI that allows for specifying the coverage of the unpausing.

### NOTES
- It was proposed to transition the governance of all V1.5 vaults to the Timelock in order to better protect strategy migrations. This means that V1.5 vaults will only be able to un-pause via the Timelock once this is applied and the script should account for this as needed.

**Comment by sajanrajdev** [comment]
@GalloDaSballo @dapp-whisperer, I am all for transitioning governance on V1.5 to the Timelock to protect migrations but we may want to discuss a little bit about the implications of blocking the other governance actions by Timelock.

**Comment by gosuto-inzasheru** [comment]
can someone powerful enough attach this to the msig project board?

**Comment by sajanrajdev** [comment]
In an effort to further decentralize our infrastructure and with the imminent launch of eBTC (which is not pausable) most of our vaults have been deprecated. The setup of a centralized pausing infrastructure is no longer justified since, at this point 4 out of the 8 live vaults can be paused through GAC and the rest (Aura vaults) can be paused manually. That means that 5 transactions are requires to pause the entire vault infrastructure in case of an emergency, not to mention that there are plans to further deprecate more of our vaults.

For these reasons, all tickets related to the badger emergency toolkit will be closed for the time being.
